### ISSUE TITLE
Possible ExceptionInInitializerError with static fields 

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#21]
Given:
```java
@Data
abstract class Nat {
  interface Cases<R> {
    R Zero();
    R Suc(Nat nat);
  }
  public abstract <R> R match(Cases<R> cases);

  private static Function<Nat, Integer> eval =
     Nats.cases().Zero( ()        -> 0)
        .Suc(nat  -> eval(nat) + 1);

  public static Integer eval(Nat nat) {
    return eval.apply(nat);
  }
}
```
When executing
```java
public class Main {
  public static void main(String[] args) {
    Nat nat = Suc(Suc(Suc(Suc(Zero()))));
    System.out.println(eval(nat));
  }
}
```
You get
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jomaveger.lambda.adt.Nats.<clinit>(Nats.java:10)
	at org.jomaveger.lambda.main.Main.main(Main.java:15)
Caused by: java.lang.NullPointerException
	at org.jomaveger.lambda.adt.Nat.<clinit>(Nat.java:21)
	... 2 more
```
Due to:
* the Zero constructor being eagerly cached in a static final field in the generated class.
* a static field in Nat make use (indirectly) of another static field of the generated class.
This cylcle in the initialization dependencies trigger a nullpointer exception.

To avoid this, the Zero constructor must not be eagerly initialized.

**Comment by jbgi** [comment]
Thanks to José María for reporting the issue!
