### ISSUE TITLE
Unable to use primitives in values

### ISSUE THREAD

**Issue by talios** [derive4j/derive4j#48]
I changed one of my objects to include a `boolean` and got this:

```
[INFO] Compiling 9 source files to /Users/amrk/IdeaProjects/upstream/halbuilder/halbuilder-core/target/classes
java.lang.IllegalArgumentException: boolean
	at com.sun.tools.javac.model.JavacTypes.getDeclaredType0(JavacTypes.java:252)
	at com.sun.tools.javac.model.JavacTypes.getDeclaredType(JavacTypes.java:222)
	at org.derive4j.processor.DeriveUtilsImpl.resolve(DeriveUtilsImpl.java:137)
	at org.derive4j.processor.derivator.GettersDerivator.visitorDispatchLensGetterImpl(GettersDerivator.java:197)
	at org.derive4j.processor.derivator.GettersDerivator.lambda$generateLensGetter$10(GettersDerivator.java:173)
```

I guess derive4j doesn't support primitives?  Should it?  Or should gracefully fail, I switched to `Boolean` for now anyway.

**Comment by talios** [comment]
I notice we generate `getTemplated` as well for the accessor, should that be `isTemplated`?
